version: '3.8'
services:
  web:
    build: ./flaskr
    volumes:
      - type: bind
        source: ./web_scrapper
        target: /app/web_scrapper
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongodb
      - GITHUB_TOKEN=<your-github-token>
      - GITHUB_REPO_NAME=<your-github-username>/<your-github-repo-name>
      - GITHUB_BRANCH_NAME=<your-github-branch-name>
    depends_on:
      - mongodb
  scrapper:
    build: ./web_scrapper
    volumes:
      - type: bind
        source: ./web_scrapper
        target: /app/web_scrapper
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: