apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskr
  template:
    metadata:
      labels:
        app: flaskr
    spec:
      containers:
        - name: flask
          image: voxten/python-docker-web:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: mongodb-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "pass"
            - name: FLASK_ENV
              value: "production"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: token
            - name: GITHUB_REPO_NAME
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: repo_name
            - name: GITHUB_BRANCH_NAME
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: branch_name
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flaskr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000