apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
data:
  token: "Z2hwX3U2bVF6ZW83akttRjBxSW5zaTFpemdmdVFpTE5yTzNuUWtNaA=="
  repo_name: "dm94dGVuL3dlYi1zY3JhcHBlcg=="
  branch_name: "bWFzdGVy"